"""
Cascade surrogate training.

The surrogate learns the ARIO mapping  (disruption params) → (cascade outputs)  so the
Anticipatory Sandbox and the System-5 UI slider can get a cascade estimate in <1ms
instead of running the iterative ARIO each time.

Training data is SYNTHETIC — generated by sweeping ARIO over random disruption
parameters. No external data needed; ARIO is the ground truth the surrogate imitates.

For SAGE's fixed India supply-chain topology the inputs that vary are the disruption
scalars, so a tree-ensemble regression emulates ARIO well and runs CPU-fast. A torch
GraphSAGE/GAT (gnn/model.py torch path) is the upgrade for when graph *structure* varies.

Run:  python -m scenario_agent.gnn.train
"""
from __future__ import annotations

import os
import random

import numpy as np

from scenario_agent.ario import ARIOParams, run as run_ario

# Inputs the surrogate varies (the rest are fixed national constants).
FEATURES = [
    "disruption_fraction", "disruption_days", "spr_fill_frac",
    "bypass_capacity_mbpd", "bypass_ramp_days", "refinery_inventory_days",
]
# Outputs the surrogate predicts (ARIOResult scalars).
TARGETS = [
    "gap_mbpd", "gap_duration_days", "spr_depletion_days",
    "price_impact_low", "price_impact_high", "gdp_proxy_impact_pct",
]

WEIGHTS_PATH = "scenario_agent/gnn/weights/cascade_surrogate.joblib"


def generate_training_data(n_samples: int = 5000, seed: int = 7):
    """Sweep ARIO over random disruption params → (X features, y targets)."""
    rng = random.Random(seed)
    X, y = [], []
    for _ in range(n_samples):
        p = ARIOParams(
            disruption_fraction=rng.uniform(0.05, 1.0),
            disruption_days=rng.randint(5, 90),
            spr_fill_frac=rng.uniform(0.15, 1.0),
            bypass_capacity_mbpd=rng.uniform(2.0, 5.5),
            bypass_ramp_days=rng.uniform(2.0, 12.0),
            refinery_inventory_days=rng.uniform(10.0, 30.0),
        )
        r = run_ario(p)
        X.append([getattr(p, f) for f in FEATURES])
        y.append([getattr(r, t) for t in TARGETS])
    return np.array(X, dtype=float), np.array(y, dtype=float)


def train(output_path: str = WEIGHTS_PATH, n_samples: int = 5000) -> dict:
    """Fit the surrogate, report held-out accuracy, save weights. Returns metrics."""
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.model_selection import train_test_split
    import joblib

    X, y = generate_training_data(n_samples)
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=7)

    model = RandomForestRegressor(n_estimators=150, n_jobs=-1, random_state=7)
    model.fit(Xtr, ytr)

    pred = model.predict(Xte)
    mae = np.mean(np.abs(pred - yte), axis=0)
    ss_res = np.sum((yte - pred) ** 2, axis=0)
    ss_tot = np.sum((yte - yte.mean(axis=0)) ** 2, axis=0) + 1e-9
    r2 = 1.0 - ss_res / ss_tot

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    joblib.dump({"model": model, "features": FEATURES, "targets": TARGETS}, output_path)

    metrics = {t: {"mae": round(float(mae[i]), 4), "r2": round(float(r2[i]), 4)}
               for i, t in enumerate(TARGETS)}
    return {"n_samples": n_samples, "saved": output_path, "per_target": metrics}


if __name__ == "__main__":
    import json
    print(json.dumps(train(), indent=2))
